---
applications:
  - name: base-predix-template-ui-dev
    memory: 1G
    instances: 1
    buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git#v1.6.56
    command: npm start
    path: dist
services:
env:
    node_env: cloud
